version: "3.9"

services:
    postgres:
        image: postgres:16
        container_name: portfolio-postgres

        environment:
            POSTGRES_DB: portfolio
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

        ports:
            - "6472:5432"

        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
